### ISSUE TITLE
Ubuntu 20.04 - qemu: error reading initrd initrd.img

### ISSUE THREAD

**Issue by Goclipse27** [jackos/jackos.io#1]
This is the error I am encountering while running below command

`qemu-system-x86_64 -nographic -kernel vmlinux -initrd initrd.img -nic user,model=rtl8139,hostfwd=tcp::5555-:23
qemu: error reading initrd initrd.img: Failed to open file “initrd.img”: open() failed: No such file or directory
`

Note: However below command succeds

- make allnoconfig qemu-busybox-min.config rust.config
- make
- make menuconfig - sample echo server
- make -> built bzImage succeds with the changes

I am wondering which process creates initrd.img in linux folder

Note: There is one initrd.img in my /boot folder looks like that is my host ubuntu linux image.

**Comment by jackos** [comment]
[You can find the initrd.img here](https://github.com/jackos/linux/blob/tutorial-start/initrd.img)

It's there if you clone my fork, but I'll update the guide to mention where this is if someone clones the official repo instead thanks

**Comment by Goclipse27** [comment]
Thanks @jackos . I did some trick scp from the guest and did the work locally. By the way, while exploring I came across building process of init ram disk - https://docs.kernel.org/admin-guide/initrd.html. somehow that didn't work for me.

If it is follow-able decent amount of steps, we can do that too.

**Comment by jackos** [comment]
Oh nice find, I'll link this in as well in case someone wants to build their own initrd
